# Generated by Django 5.2.8 on 2025-11-16 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Celery Завдання')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та Час Створення')),
                ('number_to_calculate', models.DecimalField(decimal_places=0, max_digits=30, verbose_name='Число')),
                ('precision', models.IntegerField(default=50000, verbose_name='Точність (к-ть знаків)')),
                ('status', models.CharField(choices=[('PENDING', 'Очікує виконання'), ('RUNNING', 'Виконується'), ('SUCCESS', 'Успішно завершено'), ('FAILURE', 'Помилка виконання'), ('CANCELED', 'Скасовано'), ('REJECTED', 'Відхилено (перевищення ліміту)')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('progress_percent', models.IntegerField(default=0, verbose_name='Прогрес (%)')),
                ('result_data', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата Завершення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Обчислювальне Завдання',
                'verbose_name_plural': 'Обчислювальні Завдання',
                'ordering': ['-created_at'],
            },
        ),
    ]
