# Generated by Django 5.2.8 on 2025-11-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationtask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата Початку'),
        ),
    ]
